[package]
name = "metadata"
version = "0.10.0"
authors = ["Kazakov Giorgi Vladimirovich", "Sidorov Roman Alexandrovich"]
edition = "2024"

[dependencies]
# chrono = { version = "0.4.44", features = ["serde"] }
egui = { version = "0.34.1", optional = true }
egui-phosphor = { version = "0.12.0", optional = true }
egui_extras = { version = "0.34.1", features = [
    "datepicker",
    "serde",
], optional = true }
itertools = "0.14.0"
jiff = { version = "0.2.23", features = ["serde"] }
polars = { git = "https://github.com/pola-rs/polars", rev = "099564e", default-features = false, features = [
    "serde",
], optional = true }
semver = { version = "1.0.28", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive", "std"] }
thiserror = "2.0.18"
tracing = "0.1.44"

[features]
default = ["egui", "polars"]
egui = ["dep:egui", "dep:egui-phosphor", "dep:egui_extras"]
polars = ["dep:polars"]
