Metadata_Author = Author
    .hover = Author's first and last name.
Metadata_Date = Date
    .hover = Date the data was created or last modified.
Metadata_Description = Description
    .hover = Data description.
Metadata_Name = Name
    .hover = Data name.
Metadata_Version = Version
    .hover = Data version.
Metadata_Identifier = Identifier
    .hover = Data identifier.
